/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateEventRequest,
  EventResponse,
  GetEventsByRangeDataParams,
  UpdateEventRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getAllEvents = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<EventResponse[]>(
      {url: `/events`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllEventsQueryKey = () => {
    return [
    `/events`
    ] as const;
    }

    
export const getGetAllEventsQueryOptions = <TData = Awaited<ReturnType<typeof getAllEvents>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEvents>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllEventsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllEvents>>> = ({ signal }) => getAllEvents(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllEvents>>>
export type GetAllEventsQueryError = unknown


export function useGetAllEvents<TData = Awaited<ReturnType<typeof getAllEvents>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllEvents>>,
          TError,
          Awaited<ReturnType<typeof getAllEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllEvents<TData = Awaited<ReturnType<typeof getAllEvents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllEvents>>,
          TError,
          Awaited<ReturnType<typeof getAllEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllEvents<TData = Awaited<ReturnType<typeof getAllEvents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEvents>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllEvents<TData = Awaited<ReturnType<typeof getAllEvents>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEvents>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllEventsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const createEvent = (
    createEventRequest: CreateEventRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<EventResponse>(
      {url: `/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventRequest, signal
    },
      );
    }
  


export const getCreateEventMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventRequest}, TContext> => {

const mutationKey = ['createEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEvent>>, {data: CreateEventRequest}> = (props) => {
          const {data} = props ?? {};

          return  createEvent(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEventMutationResult = NonNullable<Awaited<ReturnType<typeof createEvent>>>
    export type CreateEventMutationBody = CreateEventRequest
    export type CreateEventMutationError = unknown

    export const useCreateEvent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEvent>>,
        TError,
        {data: CreateEventRequest},
        TContext
      > => {
      return useMutation(getCreateEventMutationOptions(options), queryClient);
    }
    export const getEventsByRangeData = (
    params: GetEventsByRangeDataParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<EventResponse[]>(
      {url: `/events/range-data`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetEventsByRangeDataQueryKey = (params?: GetEventsByRangeDataParams,) => {
    return [
    `/events/range-data`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetEventsByRangeDataQueryOptions = <TData = Awaited<ReturnType<typeof getEventsByRangeData>>, TError = unknown>(params: GetEventsByRangeDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsByRangeData>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventsByRangeDataQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventsByRangeData>>> = ({ signal }) => getEventsByRangeData(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventsByRangeData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventsByRangeDataQueryResult = NonNullable<Awaited<ReturnType<typeof getEventsByRangeData>>>
export type GetEventsByRangeDataQueryError = unknown


export function useGetEventsByRangeData<TData = Awaited<ReturnType<typeof getEventsByRangeData>>, TError = unknown>(
 params: GetEventsByRangeDataParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsByRangeData>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsByRangeData>>,
          TError,
          Awaited<ReturnType<typeof getEventsByRangeData>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventsByRangeData<TData = Awaited<ReturnType<typeof getEventsByRangeData>>, TError = unknown>(
 params: GetEventsByRangeDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsByRangeData>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsByRangeData>>,
          TError,
          Awaited<ReturnType<typeof getEventsByRangeData>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventsByRangeData<TData = Awaited<ReturnType<typeof getEventsByRangeData>>, TError = unknown>(
 params: GetEventsByRangeDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsByRangeData>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEventsByRangeData<TData = Awaited<ReturnType<typeof getEventsByRangeData>>, TError = unknown>(
 params: GetEventsByRangeDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsByRangeData>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventsByRangeDataQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getEventById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<EventResponse>(
      {url: `/events/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetEventByIdQueryKey = (id: number,) => {
    return [
    `/events/${id}`
    ] as const;
    }

    
export const getGetEventByIdQueryOptions = <TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventById>>> = ({ signal }) => getEventById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEventById>>>
export type GetEventByIdQueryError = unknown


export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEventById<TData = Awaited<ReturnType<typeof getEventById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateEvent = (
    id: number,
    updateEventRequest: UpdateEventRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<EventResponse>(
      {url: `/events/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateEventRequest, signal
    },
      );
    }
  


export const getUpdateEventMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{id: number;data: UpdateEventRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{id: number;data: UpdateEventRequest}, TContext> => {

const mutationKey = ['updateEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEvent>>, {id: number;data: UpdateEventRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateEvent(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEventMutationResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>
    export type UpdateEventMutationBody = UpdateEventRequest
    export type UpdateEventMutationError = unknown

    export const useUpdateEvent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{id: number;data: UpdateEventRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEvent>>,
        TError,
        {id: number;data: UpdateEventRequest},
        TContext
      > => {
      return useMutation(getUpdateEventMutationOptions(options), queryClient);
    }
    export const deleteEvent = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/events/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteEventMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEvent>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteEvent(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEventMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>
    
    export type DeleteEventMutationError = unknown

    export const useDeleteEvent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEvent>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteEventMutationOptions(options), queryClient);
    }
    