/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  CreateStatoRiparazioneRequest,
  StatoRiparazioneResponse,
  UpdateStatoRiparazioneRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getAllStatoRiparazione = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<StatoRiparazioneResponse[]>(
      {url: `/api/stato-riparazione`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllStatoRiparazioneQueryKey = () => {
    return [
    `/api/stato-riparazione`
    ] as const;
    }

    
export const getGetAllStatoRiparazioneQueryOptions = <TData = Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllStatoRiparazioneQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllStatoRiparazione>>> = ({ signal }) => getAllStatoRiparazione(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllStatoRiparazioneQueryResult = NonNullable<Awaited<ReturnType<typeof getAllStatoRiparazione>>>
export type GetAllStatoRiparazioneQueryError = ApiError


export function useGetAllStatoRiparazione<TData = Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllStatoRiparazione>>,
          TError,
          Awaited<ReturnType<typeof getAllStatoRiparazione>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllStatoRiparazione<TData = Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllStatoRiparazione>>,
          TError,
          Awaited<ReturnType<typeof getAllStatoRiparazione>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllStatoRiparazione<TData = Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllStatoRiparazione<TData = Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllStatoRiparazione>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllStatoRiparazioneQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateAllStatoRiparazione = (
    updateStatoRiparazioneRequest: UpdateStatoRiparazioneRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<StatoRiparazioneResponse[]>(
      {url: `/api/stato-riparazione`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateStatoRiparazioneRequest, signal
    },
      );
    }
  


export const getUpdateAllStatoRiparazioneMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAllStatoRiparazione>>, TError,{data: UpdateStatoRiparazioneRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateAllStatoRiparazione>>, TError,{data: UpdateStatoRiparazioneRequest}, TContext> => {

const mutationKey = ['updateAllStatoRiparazione'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAllStatoRiparazione>>, {data: UpdateStatoRiparazioneRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateAllStatoRiparazione(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAllStatoRiparazioneMutationResult = NonNullable<Awaited<ReturnType<typeof updateAllStatoRiparazione>>>
    export type UpdateAllStatoRiparazioneMutationBody = UpdateStatoRiparazioneRequest
    export type UpdateAllStatoRiparazioneMutationError = ApiError

    export const useUpdateAllStatoRiparazione = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAllStatoRiparazione>>, TError,{data: UpdateStatoRiparazioneRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAllStatoRiparazione>>,
        TError,
        {data: UpdateStatoRiparazioneRequest},
        TContext
      > => {
      return useMutation(getUpdateAllStatoRiparazioneMutationOptions(options), queryClient);
    }
    export const createStatoRiparazione = (
    createStatoRiparazioneRequest: CreateStatoRiparazioneRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<StatoRiparazioneResponse>(
      {url: `/api/stato-riparazione`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStatoRiparazioneRequest, signal
    },
      );
    }
  


export const getCreateStatoRiparazioneMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStatoRiparazione>>, TError,{data: CreateStatoRiparazioneRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createStatoRiparazione>>, TError,{data: CreateStatoRiparazioneRequest}, TContext> => {

const mutationKey = ['createStatoRiparazione'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStatoRiparazione>>, {data: CreateStatoRiparazioneRequest}> = (props) => {
          const {data} = props ?? {};

          return  createStatoRiparazione(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStatoRiparazioneMutationResult = NonNullable<Awaited<ReturnType<typeof createStatoRiparazione>>>
    export type CreateStatoRiparazioneMutationBody = CreateStatoRiparazioneRequest
    export type CreateStatoRiparazioneMutationError = ApiError

    export const useCreateStatoRiparazione = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStatoRiparazione>>, TError,{data: CreateStatoRiparazioneRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStatoRiparazione>>,
        TError,
        {data: CreateStatoRiparazioneRequest},
        TContext
      > => {
      return useMutation(getCreateStatoRiparazioneMutationOptions(options), queryClient);
    }
    export const getStatoRiparazioneById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<StatoRiparazioneResponse>(
      {url: `/api/stato-riparazione/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetStatoRiparazioneByIdQueryKey = (id: number,) => {
    return [
    `/api/stato-riparazione/${id}`
    ] as const;
    }

    
export const getGetStatoRiparazioneByIdQueryOptions = <TData = Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError = ApiError>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatoRiparazioneByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatoRiparazioneById>>> = ({ signal }) => getStatoRiparazioneById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatoRiparazioneByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStatoRiparazioneById>>>
export type GetStatoRiparazioneByIdQueryError = ApiError


export function useGetStatoRiparazioneById<TData = Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError = ApiError>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatoRiparazioneById>>,
          TError,
          Awaited<ReturnType<typeof getStatoRiparazioneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatoRiparazioneById<TData = Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatoRiparazioneById>>,
          TError,
          Awaited<ReturnType<typeof getStatoRiparazioneById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatoRiparazioneById<TData = Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStatoRiparazioneById<TData = Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatoRiparazioneById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatoRiparazioneByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const deleteStatoRiparazione = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/stato-riparazione/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteStatoRiparazioneMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStatoRiparazione>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteStatoRiparazione>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteStatoRiparazione'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStatoRiparazione>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteStatoRiparazione(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStatoRiparazioneMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStatoRiparazione>>>
    
    export type DeleteStatoRiparazioneMutationError = ApiError

    export const useDeleteStatoRiparazione = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStatoRiparazione>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStatoRiparazione>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteStatoRiparazioneMutationOptions(options), queryClient);
    }
    