/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProductRequest,
  ProductResponse,
  SearchProductsParams
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getAllProducts = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse[]>(
      {url: `/products`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllProductsQueryKey = () => {
    return [
    `/products`
    ] as const;
    }

    
export const getGetAllProductsQueryOptions = <TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProducts>>> = ({ signal }) => getAllProducts(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProducts>>>
export type GetAllProductsQueryError = unknown


export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchProducts = (
    params: SearchProductsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse[]>(
      {url: `/products/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchProductsQueryKey = (params?: SearchProductsParams,) => {
    return [
    `/products/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchProductsQueryOptions = <TData = Awaited<ReturnType<typeof searchProducts>>, TError = unknown>(params: SearchProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProducts>>> = ({ signal }) => searchProducts(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchProductsQueryResult = NonNullable<Awaited<ReturnType<typeof searchProducts>>>
export type SearchProductsQueryError = unknown


export function useSearchProducts<TData = Awaited<ReturnType<typeof searchProducts>>, TError = unknown>(
 params: SearchProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProducts>>,
          TError,
          Awaited<ReturnType<typeof searchProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProducts<TData = Awaited<ReturnType<typeof searchProducts>>, TError = unknown>(
 params: SearchProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProducts>>,
          TError,
          Awaited<ReturnType<typeof searchProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProducts<TData = Awaited<ReturnType<typeof searchProducts>>, TError = unknown>(
 params: SearchProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchProducts<TData = Awaited<ReturnType<typeof searchProducts>>, TError = unknown>(
 params: SearchProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProducts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getProductBySeriale = (
    seriale: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/products/by-seriale/${seriale}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductBySerialeQueryKey = (seriale: string,) => {
    return [
    `/products/by-seriale/${seriale}`
    ] as const;
    }

    
export const getGetProductBySerialeQueryOptions = <TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = unknown>(seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductBySerialeQueryKey(seriale);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductBySeriale>>> = ({ signal }) => getProductBySeriale(seriale, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(seriale), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductBySerialeQueryResult = NonNullable<Awaited<ReturnType<typeof getProductBySeriale>>>
export type GetProductBySerialeQueryError = unknown


export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = unknown>(
 seriale: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductBySeriale>>,
          TError,
          Awaited<ReturnType<typeof getProductBySeriale>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = unknown>(
 seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductBySeriale>>,
          TError,
          Awaited<ReturnType<typeof getProductBySeriale>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = unknown>(
 seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = unknown>(
 seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductBySerialeQueryOptions(seriale,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getProductByImei = (
    imei: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/products/by-imei/${imei}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductByImeiQueryKey = (imei: string,) => {
    return [
    `/products/by-imei/${imei}`
    ] as const;
    }

    
export const getGetProductByImeiQueryOptions = <TData = Awaited<ReturnType<typeof getProductByImei>>, TError = unknown>(imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductByImeiQueryKey(imei);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductByImei>>> = ({ signal }) => getProductByImei(imei, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(imei), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductByImeiQueryResult = NonNullable<Awaited<ReturnType<typeof getProductByImei>>>
export type GetProductByImeiQueryError = unknown


export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = unknown>(
 imei: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductByImei>>,
          TError,
          Awaited<ReturnType<typeof getProductByImei>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = unknown>(
 imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductByImei>>,
          TError,
          Awaited<ReturnType<typeof getProductByImei>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = unknown>(
 imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = unknown>(
 imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByImeiQueryOptions(imei,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getProductById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/products/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductByIdQueryKey = (id: number,) => {
    return [
    `/products/${id}`
    ] as const;
    }

    
export const getGetProductByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductById>>> = ({ signal }) => getProductById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>
export type GetProductByIdQueryError = unknown


export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateProduct = (
    id: number,
    createProductRequest: CreateProductRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/products/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: createProductRequest, signal
    },
      );
    }
  


export const getUpdateProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: CreateProductRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: CreateProductRequest}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {id: number;data: CreateProductRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProduct(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = CreateProductRequest
    export type UpdateProductMutationError = unknown

    export const useUpdateProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: CreateProductRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {id: number;data: CreateProductRequest},
        TContext
      > => {
      return useMutation(getUpdateProductMutationOptions(options), queryClient);
    }
    export const deleteProduct = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/products/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteProduct(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>
    
    export type DeleteProductMutationError = unknown

    export const useDeleteProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteProductMutationOptions(options), queryClient);
    }
    