/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateInterventionRequest,
  GetAllInterventionsParams,
  InterventionResponse,
  PaginatedResponseInterventionResponse,
  SearchInterventionsByModelParams,
  SearchInterventionsParams,
  UpdateInterventionRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const createIntervention = (
    createInterventionRequest: CreateInterventionRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/interventions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInterventionRequest, signal
    },
      );
    }
  


export const getCreateInterventionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIntervention>>, TError,{data: CreateInterventionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createIntervention>>, TError,{data: CreateInterventionRequest}, TContext> => {

const mutationKey = ['createIntervention'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIntervention>>, {data: CreateInterventionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createIntervention(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateInterventionMutationResult = NonNullable<Awaited<ReturnType<typeof createIntervention>>>
    export type CreateInterventionMutationBody = CreateInterventionRequest
    export type CreateInterventionMutationError = unknown

    export const useCreateIntervention = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIntervention>>, TError,{data: CreateInterventionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createIntervention>>,
        TError,
        {data: CreateInterventionRequest},
        TContext
      > => {
      return useMutation(getCreateInterventionMutationOptions(options), queryClient);
    }
    export const getAllInterventions = (
    params?: GetAllInterventionsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<PaginatedResponseInterventionResponse>(
      {url: `/interventions`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllInterventionsQueryKey = (params?: GetAllInterventionsParams,) => {
    return [
    `/interventions`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllInterventionsQueryOptions = <TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = unknown>(params?: GetAllInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllInterventionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllInterventions>>> = ({ signal }) => getAllInterventions(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllInterventionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllInterventions>>>
export type GetAllInterventionsQueryError = unknown


export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = unknown>(
 params: undefined |  GetAllInterventionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllInterventions>>,
          TError,
          Awaited<ReturnType<typeof getAllInterventions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = unknown>(
 params?: GetAllInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllInterventions>>,
          TError,
          Awaited<ReturnType<typeof getAllInterventions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = unknown>(
 params?: GetAllInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = unknown>(
 params?: GetAllInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllInterventionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInterventiGenerali = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/interventions/generali`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventiGeneraliQueryKey = () => {
    return [
    `/interventions/generali`
    ] as const;
    }

    
export const getGetInterventiGeneraliQueryOptions = <TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventiGeneraliQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventiGenerali>>> = ({ signal }) => getInterventiGenerali(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventiGeneraliQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventiGenerali>>>
export type GetInterventiGeneraliQueryError = unknown


export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventiGenerali>>,
          TError,
          Awaited<ReturnType<typeof getInterventiGenerali>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventiGenerali>>,
          TError,
          Awaited<ReturnType<typeof getInterventiGenerali>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventiGeneraliQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchInterventions = (
    params: SearchInterventionsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/interventions/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchInterventionsQueryKey = (params?: SearchInterventionsParams,) => {
    return [
    `/interventions/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchInterventionsQueryOptions = <TData = Awaited<ReturnType<typeof searchInterventions>>, TError = unknown>(params: SearchInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchInterventionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchInterventions>>> = ({ signal }) => searchInterventions(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchInterventions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchInterventionsQueryResult = NonNullable<Awaited<ReturnType<typeof searchInterventions>>>
export type SearchInterventionsQueryError = unknown


export function useSearchInterventions<TData = Awaited<ReturnType<typeof searchInterventions>>, TError = unknown>(
 params: SearchInterventionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInterventions>>,
          TError,
          Awaited<ReturnType<typeof searchInterventions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchInterventions<TData = Awaited<ReturnType<typeof searchInterventions>>, TError = unknown>(
 params: SearchInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInterventions>>,
          TError,
          Awaited<ReturnType<typeof searchInterventions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchInterventions<TData = Awaited<ReturnType<typeof searchInterventions>>, TError = unknown>(
 params: SearchInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchInterventions<TData = Awaited<ReturnType<typeof searchInterventions>>, TError = unknown>(
 params: SearchInterventionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchInterventionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchInterventionsByModel = (
    params: SearchInterventionsByModelParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/interventions/search/by-model`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchInterventionsByModelQueryKey = (params?: SearchInterventionsByModelParams,) => {
    return [
    `/interventions/search/by-model`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchInterventionsByModelQueryOptions = <TData = Awaited<ReturnType<typeof searchInterventionsByModel>>, TError = unknown>(params: SearchInterventionsByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionsByModel>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchInterventionsByModelQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchInterventionsByModel>>> = ({ signal }) => searchInterventionsByModel(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchInterventionsByModel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchInterventionsByModelQueryResult = NonNullable<Awaited<ReturnType<typeof searchInterventionsByModel>>>
export type SearchInterventionsByModelQueryError = unknown


export function useSearchInterventionsByModel<TData = Awaited<ReturnType<typeof searchInterventionsByModel>>, TError = unknown>(
 params: SearchInterventionsByModelParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionsByModel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInterventionsByModel>>,
          TError,
          Awaited<ReturnType<typeof searchInterventionsByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchInterventionsByModel<TData = Awaited<ReturnType<typeof searchInterventionsByModel>>, TError = unknown>(
 params: SearchInterventionsByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionsByModel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInterventionsByModel>>,
          TError,
          Awaited<ReturnType<typeof searchInterventionsByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchInterventionsByModel<TData = Awaited<ReturnType<typeof searchInterventionsByModel>>, TError = unknown>(
 params: SearchInterventionsByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionsByModel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchInterventionsByModel<TData = Awaited<ReturnType<typeof searchInterventionsByModel>>, TError = unknown>(
 params: SearchInterventionsByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionsByModel>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchInterventionsByModelQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInterventionsByModel = (
    modelId: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/interventions/by-model/${modelId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventionsByModelQueryKey = (modelId: number,) => {
    return [
    `/interventions/by-model/${modelId}`
    ] as const;
    }

    
export const getGetInterventionsByModelQueryOptions = <TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = unknown>(modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventionsByModelQueryKey(modelId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventionsByModel>>> = ({ signal }) => getInterventionsByModel(modelId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(modelId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventionsByModelQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventionsByModel>>>
export type GetInterventionsByModelQueryError = unknown


export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = unknown>(
 modelId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionsByModel>>,
          TError,
          Awaited<ReturnType<typeof getInterventionsByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = unknown>(
 modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionsByModel>>,
          TError,
          Awaited<ReturnType<typeof getInterventionsByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = unknown>(
 modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = unknown>(
 modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventionsByModelQueryOptions(modelId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInterventionByName = (
    nome: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/interventions/by-name/${nome}`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventionByNameQueryKey = (nome: string,) => {
    return [
    `/interventions/by-name/${nome}`
    ] as const;
    }

    
export const getGetInterventionByNameQueryOptions = <TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = unknown>(nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventionByNameQueryKey(nome);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventionByName>>> = ({ signal }) => getInterventionByName(nome, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(nome), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventionByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventionByName>>>
export type GetInterventionByNameQueryError = unknown


export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = unknown>(
 nome: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionByName>>,
          TError,
          Awaited<ReturnType<typeof getInterventionByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionByName>>,
          TError,
          Awaited<ReturnType<typeof getInterventionByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventionByNameQueryOptions(nome,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInterventionById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/interventions/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventionByIdQueryKey = (id: number,) => {
    return [
    `/interventions/${id}`
    ] as const;
    }

    
export const getGetInterventionByIdQueryOptions = <TData = Awaited<ReturnType<typeof getInterventionById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventionByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventionById>>> = ({ signal }) => getInterventionById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventionById>>>
export type GetInterventionByIdQueryError = unknown


export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionById>>,
          TError,
          Awaited<ReturnType<typeof getInterventionById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionById>>,
          TError,
          Awaited<ReturnType<typeof getInterventionById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventionByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateIntervention = (
    id: number,
    updateInterventionRequest: UpdateInterventionRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/interventions/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateInterventionRequest, signal
    },
      );
    }
  


export const getUpdateInterventionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIntervention>>, TError,{id: number;data: UpdateInterventionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateIntervention>>, TError,{id: number;data: UpdateInterventionRequest}, TContext> => {

const mutationKey = ['updateIntervention'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateIntervention>>, {id: number;data: UpdateInterventionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateIntervention(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateInterventionMutationResult = NonNullable<Awaited<ReturnType<typeof updateIntervention>>>
    export type UpdateInterventionMutationBody = UpdateInterventionRequest
    export type UpdateInterventionMutationError = unknown

    export const useUpdateIntervention = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIntervention>>, TError,{id: number;data: UpdateInterventionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateIntervention>>,
        TError,
        {id: number;data: UpdateInterventionRequest},
        TContext
      > => {
      return useMutation(getUpdateInterventionMutationOptions(options), queryClient);
    }
    export const deleteIntervention = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/interventions/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteInterventionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIntervention>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteIntervention>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteIntervention'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIntervention>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteIntervention(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteInterventionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIntervention>>>
    
    export type DeleteInterventionMutationError = unknown

    export const useDeleteIntervention = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIntervention>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteIntervention>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteInterventionMutationOptions(options), queryClient);
    }
    