/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ColorResponse,
  CreateColorRequest,
  SearchColorsParams,
  UpdateColorRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const createColor = (
    createColorRequest: CreateColorRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ColorResponse>(
      {url: `/colors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createColorRequest, signal
    },
      );
    }
  


export const getCreateColorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createColor>>, TError,{data: CreateColorRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createColor>>, TError,{data: CreateColorRequest}, TContext> => {

const mutationKey = ['createColor'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createColor>>, {data: CreateColorRequest}> = (props) => {
          const {data} = props ?? {};

          return  createColor(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateColorMutationResult = NonNullable<Awaited<ReturnType<typeof createColor>>>
    export type CreateColorMutationBody = CreateColorRequest
    export type CreateColorMutationError = unknown

    export const useCreateColor = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createColor>>, TError,{data: CreateColorRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createColor>>,
        TError,
        {data: CreateColorRequest},
        TContext
      > => {
      return useMutation(getCreateColorMutationOptions(options), queryClient);
    }
    export const getAllColors = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ColorResponse[]>(
      {url: `/colors`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllColorsQueryKey = () => {
    return [
    `/colors`
    ] as const;
    }

    
export const getGetAllColorsQueryOptions = <TData = Awaited<ReturnType<typeof getAllColors>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllColors>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllColorsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllColors>>> = ({ signal }) => getAllColors(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllColors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllColorsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllColors>>>
export type GetAllColorsQueryError = unknown


export function useGetAllColors<TData = Awaited<ReturnType<typeof getAllColors>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllColors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllColors>>,
          TError,
          Awaited<ReturnType<typeof getAllColors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllColors<TData = Awaited<ReturnType<typeof getAllColors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllColors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllColors>>,
          TError,
          Awaited<ReturnType<typeof getAllColors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllColors<TData = Awaited<ReturnType<typeof getAllColors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllColors>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllColors<TData = Awaited<ReturnType<typeof getAllColors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllColors>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllColorsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchColors = (
    params: SearchColorsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ColorResponse[]>(
      {url: `/colors/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchColorsQueryKey = (params?: SearchColorsParams,) => {
    return [
    `/colors/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchColorsQueryOptions = <TData = Awaited<ReturnType<typeof searchColors>>, TError = unknown>(params: SearchColorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchColors>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchColorsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchColors>>> = ({ signal }) => searchColors(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchColors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchColorsQueryResult = NonNullable<Awaited<ReturnType<typeof searchColors>>>
export type SearchColorsQueryError = unknown


export function useSearchColors<TData = Awaited<ReturnType<typeof searchColors>>, TError = unknown>(
 params: SearchColorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchColors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchColors>>,
          TError,
          Awaited<ReturnType<typeof searchColors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchColors<TData = Awaited<ReturnType<typeof searchColors>>, TError = unknown>(
 params: SearchColorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchColors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchColors>>,
          TError,
          Awaited<ReturnType<typeof searchColors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchColors<TData = Awaited<ReturnType<typeof searchColors>>, TError = unknown>(
 params: SearchColorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchColors>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchColors<TData = Awaited<ReturnType<typeof searchColors>>, TError = unknown>(
 params: SearchColorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchColors>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchColorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getColorByName = (
    nome: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ColorResponse>(
      {url: `/colors/by-name/${nome}`, method: 'GET', signal
    },
      );
    }
  



export const getGetColorByNameQueryKey = (nome: string,) => {
    return [
    `/colors/by-name/${nome}`
    ] as const;
    }

    
export const getGetColorByNameQueryOptions = <TData = Awaited<ReturnType<typeof getColorByName>>, TError = unknown>(nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorByName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetColorByNameQueryKey(nome);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getColorByName>>> = ({ signal }) => getColorByName(nome, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(nome), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getColorByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetColorByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getColorByName>>>
export type GetColorByNameQueryError = unknown


export function useGetColorByName<TData = Awaited<ReturnType<typeof getColorByName>>, TError = unknown>(
 nome: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColorByName>>,
          TError,
          Awaited<ReturnType<typeof getColorByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetColorByName<TData = Awaited<ReturnType<typeof getColorByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColorByName>>,
          TError,
          Awaited<ReturnType<typeof getColorByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetColorByName<TData = Awaited<ReturnType<typeof getColorByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorByName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetColorByName<TData = Awaited<ReturnType<typeof getColorByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorByName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetColorByNameQueryOptions(nome,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getColorById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ColorResponse>(
      {url: `/colors/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetColorByIdQueryKey = (id: number,) => {
    return [
    `/colors/${id}`
    ] as const;
    }

    
export const getGetColorByIdQueryOptions = <TData = Awaited<ReturnType<typeof getColorById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetColorByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getColorById>>> = ({ signal }) => getColorById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getColorById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetColorByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getColorById>>>
export type GetColorByIdQueryError = unknown


export function useGetColorById<TData = Awaited<ReturnType<typeof getColorById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColorById>>,
          TError,
          Awaited<ReturnType<typeof getColorById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetColorById<TData = Awaited<ReturnType<typeof getColorById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getColorById>>,
          TError,
          Awaited<ReturnType<typeof getColorById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetColorById<TData = Awaited<ReturnType<typeof getColorById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetColorById<TData = Awaited<ReturnType<typeof getColorById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getColorById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetColorByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateColor = (
    id: number,
    updateColorRequest: UpdateColorRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ColorResponse>(
      {url: `/colors/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateColorRequest, signal
    },
      );
    }
  


export const getUpdateColorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateColor>>, TError,{id: number;data: UpdateColorRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateColor>>, TError,{id: number;data: UpdateColorRequest}, TContext> => {

const mutationKey = ['updateColor'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateColor>>, {id: number;data: UpdateColorRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateColor(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateColorMutationResult = NonNullable<Awaited<ReturnType<typeof updateColor>>>
    export type UpdateColorMutationBody = UpdateColorRequest
    export type UpdateColorMutationError = unknown

    export const useUpdateColor = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateColor>>, TError,{id: number;data: UpdateColorRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateColor>>,
        TError,
        {id: number;data: UpdateColorRequest},
        TContext
      > => {
      return useMutation(getUpdateColorMutationOptions(options), queryClient);
    }
    export const deleteColor = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/colors/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteColorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteColor>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteColor>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteColor'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteColor>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteColor(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteColorMutationResult = NonNullable<Awaited<ReturnType<typeof deleteColor>>>
    
    export type DeleteColorMutationError = unknown

    export const useDeleteColor = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteColor>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteColor>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteColorMutationOptions(options), queryClient);
    }
    