export * from './endpoints/repairs/repairs';
export * from './endpoints/products/products';
export * from './endpoints/models/models';
export * from './endpoints/interventions/interventions';
export * from './endpoints/customers/customers';
export * from './endpoints/colors/colors';
export * from './endpoints/brands/brands';
export * from './endpoints/auth/auth';
export * from './endpoints/users/users';
export * from './endpoints/health/health';
export * from './endpoints/repair-details/repair-details'
export * from './models';
