/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { CreateColorRequest } from './createColorRequest';
import type { CreateModelRequest } from './createModelRequest';
import type { RecordStringStringArray } from './recordStringStringArray';

export interface CreateProductRequest {
  model: CreateModelRequest;
  color: CreateColorRequest;
  capacita?: string;
  codiceUnlock?: string;
  sequenzaUnlock?: number[];
  pin?: string;
  accessori?: string;
  contattoConLiquidi?: boolean;
  dispositivoNonTestabile?: boolean;
  acquistatoPressoDiNoi?: boolean;
  seriale?: string;
  imei?: string;
  codiceModello?: string;
  testDiagnostici?: RecordStringStringArray;
  lasciatoInNegozio?: boolean;
}
