/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProductRequest } from './createProductRequest';
import type { CreateRepairDetailsRequest } from './createRepairDetailsRequest';

export interface CreateRepairRequest {
  customerId: number;
  product: CreateProductRequest;
  details?: CreateRepairDetailsRequest;
}
