/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRepairRequestTariffa } from './createRepairRequestTariffa';

export interface CreateRepairRequest {
  customerId: number;
  productId: number;
  interventionIds?: number[];
  commenti?: string;
  dataConsegna?: string;
  tariffa: CreateRepairRequestTariffa;
  acconto?: number;
}
