/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export type CreateRepairRequestTariffa = typeof CreateRepairRequestTariffa[keyof typeof CreateRepairRequestTariffa];


export const CreateRepairRequestTariffa = {
  STANDARD: 'STANDARD',
  EXPRESS: 'EXPRESS',
} as const;
