/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { AddMessageRequest } from './addMessageRequest';

export interface CreateRepairDetailsRequest {
  isPreventivo?: boolean;
  interventionIds?: number[];
  dataConsegna?: string;
  acconto?: number;
  messaggi?: AddMessageRequest[];
}
