/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export type CreateProductRequestTipoDispositivo = typeof CreateProductRequestTipoDispositivo[keyof typeof CreateProductRequestTipoDispositivo];


export const CreateProductRequestTipoDispositivo = {
  TELEFONO: 'TELEFONO',
  TABLET: 'TABLET',
  COMPUTER: 'COMPUTER',
} as const;
