/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { TipoDispositivo } from './tipoDispositivo';

export interface CreateModelRequest {
  nome: string;
  tipoDispositivo: TipoDispositivo;
  brandNome: string;
}
