/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export type CustomerSortBy = typeof CustomerSortBy[keyof typeof CustomerSortBy];


export const CustomerSortBy = {
  nome: 'nome',
  cognome: 'cognome',
  email: 'email',
} as const;
