/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerResponse {
  id: number;
  /** @minLength 1 */
  nome: string;
  /** @minLength 1 */
  cognome: string;
  /** @minLength 1 */
  email: string;
  indirizzo?: string;
  citta?: string;
  cap?: string;
  /** @minLength 1 */
  telefono: string;
  telefonoSecondario?: string;
}
