/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { ModelSortBy } from './modelSortBy';
import type { SortOrder } from './sortOrder';

export type GetAllModelsPaginatedParams = {
page?: number;
pageSize?: number;
sortBy?: ModelSortBy;
sortOrder?: SortOrder;
nome?: string;
brandNome?: string;
tipoDispositivo?: string;
};
