/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { InterventionSortBy } from './interventionSortBy';
import type { SortOrder } from './sortOrder';

export type GetAllInterventionsParams = {
page?: number;
pageSize?: number;
sortBy?: InterventionSortBy;
sortOrder?: SortOrder;
nome?: string;
modelId?: number;
};
