/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerSortBy } from './customerSortBy';
import type { SortOrder } from './sortOrder';

export type GetAllCustomersParams = {
page?: number;
pageSize?: number;
sortBy?: CustomerSortBy;
sortOrder?: SortOrder;
nome?: string;
cognome?: string;
telefono?: string;
email?: string;
};
