/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { ProductSortBy } from './productSortBy';
import type { SortOrder } from './sortOrder';

export type GetAllProductsParams = {
page?: number;
pageSize?: number;
sortBy?: ProductSortBy;
sortOrder?: SortOrder;
modello?: string;
brand?: string;
};
