/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type GetAllBrandsPaginatedParams = {
page?: number;
pageSize?: number;
sortOrder?: SortOrder;
nome?: string;
};
