/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { HealthResponseStatus } from './healthResponseStatus';

export interface HealthResponse {
  status: HealthResponseStatus;
  timestamp: string;
  uptime: number;
}
