/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export * from './addMessageRequest';
export * from './brandResponse';
export * from './colorResponse';
export * from './createBrandRequest';
export * from './createColorRequest';
export * from './createCustomerRequest';
export * from './createInterventionRequest';
export * from './createModelRequest';
export * from './createProductRequest';
export * from './createRepairDetailsRequest';
export * from './createRepairRequest';
export * from './customerResponse';
export * from './getAllRepairsParams';
export * from './healthResponse';
export * from './healthResponseStatus';
export * from './interventionQuantitaRequest';
export * from './interventionQuantitaResponse';
export * from './interventionResponse';
export * from './loginRequest';
export * from './loginResponse';
export * from './modelResponse';
export * from './pageResponseRepairResponse';
export * from './productResponse';
export * from './recordStringStringArray';
export * from './registerRequest';
export * from './repairDetailsResponse';
export * from './repairMessageResponse';
export * from './repairResponse';
export * from './role';
export * from './searchBrandsParams';
export * from './searchColorsParams';
export * from './searchCustomersParams';
export * from './searchInterventionsByModelParams';
export * from './searchInterventionsParams';
export * from './searchModelsByBrandNameParams';
export * from './searchModelsByBrandParams';
export * from './searchModelsParams';
export * from './searchProductsParams';
export * from './searchRepairsParams';
export * from './statoRepair';
export * from './statoRiparazione';
export * from './tipoDispositivo';
export * from './updateBrandRequest';
export * from './updateColorRequest';
export * from './updateCustomerRequest';
export * from './updateInterventionRequest';
export * from './updateModelRequest';
export * from './updateProductRequest';
export * from './updateRepairDetailsRequest';
export * from './updateRepairRequest';
export * from './updateStatoRepairRequest';
export * from './updateUserRequest';
export * from './userResponse';