/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export * from './addMessageRequest';
export * from './apiError';
export * from './brandResponse';
export * from './colorResponse';
export * from './createBrandRequest';
export * from './createColorRequest';
export * from './createCustomerRequest';
export * from './createInterventionRequest';
export * from './createModelRequest';
export * from './createProductRequest';
export * from './createRepairDetailsRequest';
export * from './createRepairRequest';
export * from './createRepairRequestTariffa';
export * from './createStatoRepairRequest';
export * from './createStatoRiparazioneRequest';
export * from './customerResponse';
export * from './getAllRepairsParams';
export * from './healthCheck200';
export * from './interventionResponse';
export * from './loginRequest';
export * from './loginResponse';
export * from './modelResponse';
export * from './pageable';
export * from './pageableObject';
export * from './pageRepairResponse';
export * from './productResponse';
export * from './registerRequest';
export * from './repairDetailsResponse';
export * from './repairMessageResponse';
export * from './repairResponse';
export * from './repairResponseTariffa';
export * from './searchBrandParams';
export * from './searchColorParams';
export * from './searchCustomersParams';
export * from './searchInterventionByModelParams';
export * from './searchInterventionParams';
export * from './searchModelByBrandNameParams';
export * from './searchModelByBrandParams';
export * from './searchModelParams';
export * from './searchProductParams';
export * from './searchRepairsParams';
export * from './sortObject';
export * from './statoRepairItem';
export * from './statoRepairResponse';
export * from './statoRiparazioneItem';
export * from './statoRiparazioneResponse';
export * from './updateBrandRequest';
export * from './updateColorRequest';
export * from './updateCustomerRequest';
export * from './updateInterventionRequest';
export * from './updateModelRequest';
export * from './updateProductRequest';
export * from './updateRepairDetailsRequest';
export * from './updateRepairRequest';
export * from './updateRepairRequestTariffa';
export * from './updateStatoRepairRequest';
export * from './updateStatoRiparazioneRequest';
export * from './userResponse';
export * from './userResponseRole';