/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export type InterventionSortBy = typeof InterventionSortBy[keyof typeof InterventionSortBy];


export const InterventionSortBy = {
  nome: 'nome',
  prezzo: 'prezzo',
} as const;
