/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export interface InterventionQuantitaResponse {
  interventionId: number;
  nome: string;
  prezzo: number;
  quantita: number;
}
