/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { ModelResponseTipoDispositivo } from './modelResponseTipoDispositivo';

export interface ModelResponse {
  id: number;
  /** @minLength 1 */
  nome: string;
  tipoDispositivo: ModelResponseTipoDispositivo;
  brandId: number;
  /** @minLength 1 */
  brandNome: string;
}
