/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export type ModelSortBy = typeof ModelSortBy[keyof typeof ModelSortBy];


export const ModelSortBy = {
  nome: 'nome',
  brand: 'brand',
} as const;
