/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { ModelResponse } from './modelResponse';

export interface PaginatedResponseModelResponse {
  data: ModelResponse[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
