/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { ColorResponse } from './colorResponse';

export interface PaginatedResponseColorResponse {
  data: ColorResponse[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
