/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { InterventionResponse } from './interventionResponse';

export interface PaginatedResponseInterventionResponse {
  data: InterventionResponse[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
