/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { RepairResponse } from './repairResponse';

export interface PaginatedResponseRepairResponse {
  data: RepairResponse[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
