/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { ColorResponse } from './colorResponse';
import type { ModelResponse } from './modelResponse';
import type { ProductResponseTestDiagnostici } from './productResponseTestDiagnostici';

export interface ProductResponse {
  id: number;
  model: ModelResponse;
  color: ColorResponse;
  capacita?: string;
  codiceUnlock?: string;
  sequenzaUnlock?: number[];
  pin?: string;
  accessori?: string;
  contattoConLiquidi?: boolean;
  dispositivoNonTestabile?: boolean;
  acquistatoPressoDiNoi?: boolean;
  seriale?: string;
  imei?: string;
  codiceModello?: string;
  testDiagnostici?: ProductResponseTestDiagnostici;
}
