/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { ColorResponse } from './colorResponse';
import type { ModelResponse } from './modelResponse';
import type { RecordStringStringArray } from './recordStringStringArray';

export interface ProductResponse {
  id: number;
  model: ModelResponse;
  color: ColorResponse;
  capacita?: string;
  codiceUnlock?: string;
  sequenzaUnlock?: number[];
  pin?: string;
  accessori?: string;
  contattoConLiquidi?: boolean;
  dispositivoNonTestabile?: boolean;
  acquistatoPressoDiNoi?: boolean;
  seriale?: string;
  imei?: string;
  codiceModello?: string;
  testDiagnostici?: RecordStringStringArray;
  lasciatoInNegozio?: boolean;
}
