/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export type ProductSortBy = typeof ProductSortBy[keyof typeof ProductSortBy];


export const ProductSortBy = {
  modello: 'modello',
  brand: 'brand',
} as const;
