/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

/**
 * Construct a type with a set of properties K of type T
 */
export interface RecordStringStringArray {[key: string]: string[]}
