/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { Role } from './role';

export interface RegisterRequest {
  username: string;
  nome: string;
  email: string;
  password: string;
  role: Role;
}
