/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export type Role = typeof Role[keyof typeof Role];


export const Role = {
  ADMIN: 'ADMIN',
  COMMESSO: 'COMMESSO',
} as const;
