/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export type SearchCustomersParams = {
nome?: string;
cognome?: string;
telefono?: string;
email?: string;
};
