/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { Pageable } from './pageable';

export type SearchRepairsParams = {
statoId?: number;
statoRiparazioneId?: number;
pageable: Pageable;
};
