/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export type SearchRepairsStato = typeof SearchRepairsStato[keyof typeof SearchRepairsStato];


export const SearchRepairsStato = {
  NUOVO: 'NUOVO',
  IN_CORSO: 'IN_CORSO',
  PRONTO: 'PRONTO',
} as const;
