/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { Pageable } from './pageable';
import type { SearchRepairsStato } from './searchRepairsStato';
import type { SearchRepairsStatoRiparazione } from './searchRepairsStatoRiparazione';

export type SearchRepairsParams = {
stato?: SearchRepairsStato;
statoRiparazione?: SearchRepairsStatoRiparazione;
pageable: Pageable;
};
