/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export interface StatoRiparazioneItem {
  id: number;
  /** @minLength 1 */
  nome: string;
  /** @minLength 1 */
  colore: string;
  position: number;
}
