/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export type StatoRepair = typeof StatoRepair[keyof typeof StatoRepair];


export const StatoRepair = {
  NUOVO: 'NUOVO',
  IN_CORSO: 'IN_CORSO',
  PRONTO: 'PRONTO',
  CONSEGNATO: 'CONSEGNATO',
} as const;
