/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRepairRequestTariffa } from './updateRepairRequestTariffa';

export interface UpdateRepairRequest {
  customerId: number;
  productId: number;
  interventionIds?: number[];
  commenti?: string;
  dataConsegna?: string;
  tariffa: UpdateRepairRequestTariffa;
  acconto?: number;
  statoId?: number;
  statoRiparazioneId?: number;
}
