/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProductRequest {
  /** @minLength 1 */
  brandNome: string;
  /** @minLength 1 */
  modelNome: string;
  /** @minLength 1 */
  colorNome: string;
  capacita?: string;
  codiceUnlock?: string;
  sequenzaUnlock?: number[];
  pin?: string;
  accessori?: string;
  contattoConLiquidi?: boolean;
  dispositivoNonTestabile?: boolean;
  acquistatoPressoDiNoi?: boolean;
  seriale?: string;
  imei?: string;
  codiceModello?: string;
  tipoDispositivo?: string;
}
