/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateInterventionRequest {
  /** @minLength 1 */
  nome: string;
  prezzo: number;
  periodoGaranzia?: number;
  cumulabile?: boolean;
}
