/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */

export type UpdateRepairRequestTariffa = typeof UpdateRepairRequestTariffa[keyof typeof UpdateRepairRequestTariffa];


export const UpdateRepairRequestTariffa = {
  STANDARD: 'STANDARD',
  EXPRESS: 'EXPRESS',
} as const;
