/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { StatoRepair } from './statoRepair';
import type { StatoRiparazione } from './statoRiparazione';

export interface UpdateRepairRequest {
  customerId: number;
  stato?: StatoRepair;
  statoRiparazione?: StatoRiparazione;
}
