/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateStatoRepairRequestStato } from './updateStatoRepairRequestStato';
import type { UpdateStatoRepairRequestStatoRiparazione } from './updateStatoRepairRequestStatoRiparazione';

export interface UpdateStatoRepairRequest {
  stato?: UpdateStatoRepairRequestStato;
  statoRiparazione?: UpdateStatoRepairRequestStatoRiparazione;
}
