/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateEventRequest {
  descrizione: string;
  dataEvento: string;
  oraInizio: string;
  oraFine: string;
}
