/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { InterventionQuantitaRequest } from './interventionQuantitaRequest';

export interface UpdateRepairDetailsRequest {
  isPreventivo: boolean;
  interventi: InterventionQuantitaRequest[];
  dataConsegna?: string;
  acconto?: number;
}
