/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import type { Role } from './role';

export interface UserResponse {
  id: number;
  username: string;
  nome: string;
  email: string;
  role: Role;
  enabled: boolean;
}
