/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseRole } from './userResponseRole';

export interface UserResponse {
  id?: number;
  username?: string;
  email?: string;
  role?: UserResponseRole;
  enabled?: boolean;
}
