/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  RegisterRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const setup = (
    registerRequest: RegisterRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<string>(
      {url: `/setup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
      );
    }
  


export const getSetupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setup>>, TError,{data: RegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof setup>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['setup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setup>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  setup(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SetupMutationResult = NonNullable<Awaited<ReturnType<typeof setup>>>
    export type SetupMutationBody = RegisterRequest
    export type SetupMutationError = unknown

    export const useSetup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setup>>, TError,{data: RegisterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setup>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getSetupMutationOptions(options), queryClient);
    }
    