/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  ProductResponse,
  SearchProductParams,
  UpdateProductRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getProductById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/api/products/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductByIdQueryKey = (id: number,) => {
    return [
    `/api/products/${id}`
    ] as const;
    }

    
export const getGetProductByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductById>>, TError = ApiError>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductById>>> = ({ signal }) => getProductById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>
export type GetProductByIdQueryError = ApiError


export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = ApiError>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateProduct = (
    id: number,
    updateProductRequest: UpdateProductRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/api/products/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateProductRequest, signal
    },
      );
    }
  


export const getUpdateProductMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: UpdateProductRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: UpdateProductRequest}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {id: number;data: UpdateProductRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProduct(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = UpdateProductRequest
    export type UpdateProductMutationError = ApiError

    export const useUpdateProduct = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: UpdateProductRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {id: number;data: UpdateProductRequest},
        TContext
      > => {
      return useMutation(getUpdateProductMutationOptions(options), queryClient);
    }
    export const deleteProduct = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/products/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteProductMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteProduct(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>
    
    export type DeleteProductMutationError = ApiError

    export const useDeleteProduct = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteProductMutationOptions(options), queryClient);
    }
    export const getAllProducts = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse[]>(
      {url: `/api/products`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllProductsQueryKey = () => {
    return [
    `/api/products`
    ] as const;
    }

    
export const getGetAllProductsQueryOptions = <TData = Awaited<ReturnType<typeof getAllProducts>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProducts>>> = ({ signal }) => getAllProducts(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProducts>>>
export type GetAllProductsQueryError = ApiError


export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchProduct = (
    params: SearchProductParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse[]>(
      {url: `/api/products/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchProductQueryKey = (params?: SearchProductParams,) => {
    return [
    `/api/products/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchProductQueryOptions = <TData = Awaited<ReturnType<typeof searchProduct>>, TError = ApiError>(params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProduct>>> = ({ signal }) => searchProduct(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchProductQueryResult = NonNullable<Awaited<ReturnType<typeof searchProduct>>>
export type SearchProductQueryError = ApiError


export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ApiError>(
 params: SearchProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ApiError>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProduct>>,
          TError,
          Awaited<ReturnType<typeof searchProduct>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ApiError>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchProduct<TData = Awaited<ReturnType<typeof searchProduct>>, TError = ApiError>(
 params: SearchProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProduct>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getProductBySeriale = (
    seriale: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/api/products/by-seriale/${seriale}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductBySerialeQueryKey = (seriale: string,) => {
    return [
    `/api/products/by-seriale/${seriale}`
    ] as const;
    }

    
export const getGetProductBySerialeQueryOptions = <TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = ApiError>(seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductBySerialeQueryKey(seriale);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductBySeriale>>> = ({ signal }) => getProductBySeriale(seriale, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(seriale), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductBySerialeQueryResult = NonNullable<Awaited<ReturnType<typeof getProductBySeriale>>>
export type GetProductBySerialeQueryError = ApiError


export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = ApiError>(
 seriale: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductBySeriale>>,
          TError,
          Awaited<ReturnType<typeof getProductBySeriale>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = ApiError>(
 seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductBySeriale>>,
          TError,
          Awaited<ReturnType<typeof getProductBySeriale>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = ApiError>(
 seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductBySeriale<TData = Awaited<ReturnType<typeof getProductBySeriale>>, TError = ApiError>(
 seriale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductBySeriale>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductBySerialeQueryOptions(seriale,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getProductByImei = (
    imei: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProductResponse>(
      {url: `/api/products/by-imei/${imei}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductByImeiQueryKey = (imei: string,) => {
    return [
    `/api/products/by-imei/${imei}`
    ] as const;
    }

    
export const getGetProductByImeiQueryOptions = <TData = Awaited<ReturnType<typeof getProductByImei>>, TError = ApiError>(imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductByImeiQueryKey(imei);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductByImei>>> = ({ signal }) => getProductByImei(imei, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(imei), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductByImeiQueryResult = NonNullable<Awaited<ReturnType<typeof getProductByImei>>>
export type GetProductByImeiQueryError = ApiError


export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = ApiError>(
 imei: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductByImei>>,
          TError,
          Awaited<ReturnType<typeof getProductByImei>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = ApiError>(
 imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductByImei>>,
          TError,
          Awaited<ReturnType<typeof getProductByImei>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = ApiError>(
 imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProductByImei<TData = Awaited<ReturnType<typeof getProductByImei>>, TError = ApiError>(
 imei: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductByImei>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByImeiQueryOptions(imei,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




