/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  CreateCustomerRequest,
  CustomerResponse,
  UpdateCustomerRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getCustomerById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<CustomerResponse>(
      {url: `/api/customers/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetCustomerByIdQueryKey = (id: number,) => {
    return [
    `/api/customers/${id}`
    ] as const;
    }

    
export const getGetCustomerByIdQueryOptions = <TData = Awaited<ReturnType<typeof getCustomerById>>, TError = ApiError>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCustomerByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomerById>>> = ({ signal }) => getCustomerById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCustomerByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCustomerById>>>
export type GetCustomerByIdQueryError = ApiError


export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = ApiError>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerById>>,
          TError,
          Awaited<ReturnType<typeof getCustomerById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerById>>,
          TError,
          Awaited<ReturnType<typeof getCustomerById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCustomerByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateCustomer = (
    id: number,
    updateCustomerRequest: UpdateCustomerRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<CustomerResponse>(
      {url: `/api/customers/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomerRequest, signal
    },
      );
    }
  


export const getUpdateCustomerMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: number;data: UpdateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: number;data: UpdateCustomerRequest}, TContext> => {

const mutationKey = ['updateCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCustomer>>, {id: number;data: UpdateCustomerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCustomer(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof updateCustomer>>>
    export type UpdateCustomerMutationBody = UpdateCustomerRequest
    export type UpdateCustomerMutationError = ApiError

    export const useUpdateCustomer = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: number;data: UpdateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCustomer>>,
        TError,
        {id: number;data: UpdateCustomerRequest},
        TContext
      > => {
      return useMutation(getUpdateCustomerMutationOptions(options), queryClient);
    }
    export const deleteCustomer = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/customers/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteCustomerMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomer>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomer>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomer>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCustomer(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomer>>>
    
    export type DeleteCustomerMutationError = ApiError

    export const useDeleteCustomer = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomer>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomer>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCustomerMutationOptions(options), queryClient);
    }
    export const getAllCustomers = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<CustomerResponse[]>(
      {url: `/api/customers`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllCustomersQueryKey = () => {
    return [
    `/api/customers`
    ] as const;
    }

    
export const getGetAllCustomersQueryOptions = <TData = Awaited<ReturnType<typeof getAllCustomers>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCustomersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCustomers>>> = ({ signal }) => getAllCustomers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCustomers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCustomersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCustomers>>>
export type GetAllCustomersQueryError = ApiError


export function useGetAllCustomers<TData = Awaited<ReturnType<typeof getAllCustomers>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomers>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCustomers<TData = Awaited<ReturnType<typeof getAllCustomers>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomers>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCustomers<TData = Awaited<ReturnType<typeof getAllCustomers>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllCustomers<TData = Awaited<ReturnType<typeof getAllCustomers>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllCustomersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const createCustomer = (
    createCustomerRequest: CreateCustomerRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<CustomerResponse>(
      {url: `/api/customers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomerRequest, signal
    },
      );
    }
  


export const getCreateCustomerMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext> => {

const mutationKey = ['createCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCustomer>>, {data: CreateCustomerRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCustomer(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof createCustomer>>>
    export type CreateCustomerMutationBody = CreateCustomerRequest
    export type CreateCustomerMutationError = ApiError

    export const useCreateCustomer = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCustomer>>,
        TError,
        {data: CreateCustomerRequest},
        TContext
      > => {
      return useMutation(getCreateCustomerMutationOptions(options), queryClient);
    }
    