/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend-node
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateModelRequest,
  ModelResponse,
  SearchModelsByBrandNameParams,
  SearchModelsByBrandParams,
  SearchModelsParams,
  UpdateModelRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const createModel = (
    createModelRequest: CreateModelRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/models`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createModelRequest, signal
    },
      );
    }
  


export const getCreateModelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createModel>>, TError,{data: CreateModelRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createModel>>, TError,{data: CreateModelRequest}, TContext> => {

const mutationKey = ['createModel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createModel>>, {data: CreateModelRequest}> = (props) => {
          const {data} = props ?? {};

          return  createModel(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateModelMutationResult = NonNullable<Awaited<ReturnType<typeof createModel>>>
    export type CreateModelMutationBody = CreateModelRequest
    export type CreateModelMutationError = unknown

    export const useCreateModel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createModel>>, TError,{data: CreateModelRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createModel>>,
        TError,
        {data: CreateModelRequest},
        TContext
      > => {
      return useMutation(getCreateModelMutationOptions(options), queryClient);
    }
    export const getAllModels = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/models`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllModelsQueryKey = () => {
    return [
    `/models`
    ] as const;
    }

    
export const getGetAllModelsQueryOptions = <TData = Awaited<ReturnType<typeof getAllModels>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllModelsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllModels>>> = ({ signal }) => getAllModels(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllModelsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllModels>>>
export type GetAllModelsQueryError = unknown


export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllModels>>,
          TError,
          Awaited<ReturnType<typeof getAllModels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllModels>>,
          TError,
          Awaited<ReturnType<typeof getAllModels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllModelsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchModels = (
    params: SearchModelsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/models/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchModelsQueryKey = (params?: SearchModelsParams,) => {
    return [
    `/models/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchModelsQueryOptions = <TData = Awaited<ReturnType<typeof searchModels>>, TError = unknown>(params: SearchModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModels>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchModelsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchModels>>> = ({ signal }) => searchModels(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchModelsQueryResult = NonNullable<Awaited<ReturnType<typeof searchModels>>>
export type SearchModelsQueryError = unknown


export function useSearchModels<TData = Awaited<ReturnType<typeof searchModels>>, TError = unknown>(
 params: SearchModelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModels>>,
          TError,
          Awaited<ReturnType<typeof searchModels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModels<TData = Awaited<ReturnType<typeof searchModels>>, TError = unknown>(
 params: SearchModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModels>>,
          TError,
          Awaited<ReturnType<typeof searchModels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModels<TData = Awaited<ReturnType<typeof searchModels>>, TError = unknown>(
 params: SearchModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModels>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchModels<TData = Awaited<ReturnType<typeof searchModels>>, TError = unknown>(
 params: SearchModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModels>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchModelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchModelsByBrand = (
    params: SearchModelsByBrandParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/models/search/by-brand`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchModelsByBrandQueryKey = (params?: SearchModelsByBrandParams,) => {
    return [
    `/models/search/by-brand`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchModelsByBrandQueryOptions = <TData = Awaited<ReturnType<typeof searchModelsByBrand>>, TError = unknown>(params: SearchModelsByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrand>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchModelsByBrandQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchModelsByBrand>>> = ({ signal }) => searchModelsByBrand(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrand>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchModelsByBrandQueryResult = NonNullable<Awaited<ReturnType<typeof searchModelsByBrand>>>
export type SearchModelsByBrandQueryError = unknown


export function useSearchModelsByBrand<TData = Awaited<ReturnType<typeof searchModelsByBrand>>, TError = unknown>(
 params: SearchModelsByBrandParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrand>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelsByBrand>>,
          TError,
          Awaited<ReturnType<typeof searchModelsByBrand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelsByBrand<TData = Awaited<ReturnType<typeof searchModelsByBrand>>, TError = unknown>(
 params: SearchModelsByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrand>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelsByBrand>>,
          TError,
          Awaited<ReturnType<typeof searchModelsByBrand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelsByBrand<TData = Awaited<ReturnType<typeof searchModelsByBrand>>, TError = unknown>(
 params: SearchModelsByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrand>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchModelsByBrand<TData = Awaited<ReturnType<typeof searchModelsByBrand>>, TError = unknown>(
 params: SearchModelsByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrand>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchModelsByBrandQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchModelsByBrandName = (
    params: SearchModelsByBrandNameParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/models/search/by-brand-name`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchModelsByBrandNameQueryKey = (params?: SearchModelsByBrandNameParams,) => {
    return [
    `/models/search/by-brand-name`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchModelsByBrandNameQueryOptions = <TData = Awaited<ReturnType<typeof searchModelsByBrandName>>, TError = unknown>(params: SearchModelsByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrandName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchModelsByBrandNameQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchModelsByBrandName>>> = ({ signal }) => searchModelsByBrandName(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrandName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchModelsByBrandNameQueryResult = NonNullable<Awaited<ReturnType<typeof searchModelsByBrandName>>>
export type SearchModelsByBrandNameQueryError = unknown


export function useSearchModelsByBrandName<TData = Awaited<ReturnType<typeof searchModelsByBrandName>>, TError = unknown>(
 params: SearchModelsByBrandNameParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrandName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelsByBrandName>>,
          TError,
          Awaited<ReturnType<typeof searchModelsByBrandName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelsByBrandName<TData = Awaited<ReturnType<typeof searchModelsByBrandName>>, TError = unknown>(
 params: SearchModelsByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrandName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelsByBrandName>>,
          TError,
          Awaited<ReturnType<typeof searchModelsByBrandName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelsByBrandName<TData = Awaited<ReturnType<typeof searchModelsByBrandName>>, TError = unknown>(
 params: SearchModelsByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrandName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchModelsByBrandName<TData = Awaited<ReturnType<typeof searchModelsByBrandName>>, TError = unknown>(
 params: SearchModelsByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelsByBrandName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchModelsByBrandNameQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getModelsByBrandId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/models/by-brand-id/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetModelsByBrandIdQueryKey = (id: number,) => {
    return [
    `/models/by-brand-id/${id}`
    ] as const;
    }

    
export const getGetModelsByBrandIdQueryOptions = <TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModelsByBrandIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModelsByBrandId>>> = ({ signal }) => getModelsByBrandId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModelsByBrandIdQueryResult = NonNullable<Awaited<ReturnType<typeof getModelsByBrandId>>>
export type GetModelsByBrandIdQueryError = unknown


export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelsByBrandId>>,
          TError,
          Awaited<ReturnType<typeof getModelsByBrandId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelsByBrandId>>,
          TError,
          Awaited<ReturnType<typeof getModelsByBrandId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModelsByBrandIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getModelByName = (
    nome: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/models/by-name/${nome}`, method: 'GET', signal
    },
      );
    }
  



export const getGetModelByNameQueryKey = (nome: string,) => {
    return [
    `/models/by-name/${nome}`
    ] as const;
    }

    
export const getGetModelByNameQueryOptions = <TData = Awaited<ReturnType<typeof getModelByName>>, TError = unknown>(nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModelByNameQueryKey(nome);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModelByName>>> = ({ signal }) => getModelByName(nome, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(nome), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModelByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getModelByName>>>
export type GetModelByNameQueryError = unknown


export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = unknown>(
 nome: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelByName>>,
          TError,
          Awaited<ReturnType<typeof getModelByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelByName>>,
          TError,
          Awaited<ReturnType<typeof getModelByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = unknown>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModelByNameQueryOptions(nome,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getModelById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/models/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetModelByIdQueryKey = (id: number,) => {
    return [
    `/models/${id}`
    ] as const;
    }

    
export const getGetModelByIdQueryOptions = <TData = Awaited<ReturnType<typeof getModelById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModelByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModelById>>> = ({ signal }) => getModelById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModelByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getModelById>>>
export type GetModelByIdQueryError = unknown


export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelById>>,
          TError,
          Awaited<ReturnType<typeof getModelById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelById>>,
          TError,
          Awaited<ReturnType<typeof getModelById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModelByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateModel = (
    id: number,
    updateModelRequest: UpdateModelRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/models/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateModelRequest, signal
    },
      );
    }
  


export const getUpdateModelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateModel>>, TError,{id: number;data: UpdateModelRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateModel>>, TError,{id: number;data: UpdateModelRequest}, TContext> => {

const mutationKey = ['updateModel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateModel>>, {id: number;data: UpdateModelRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateModel(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateModelMutationResult = NonNullable<Awaited<ReturnType<typeof updateModel>>>
    export type UpdateModelMutationBody = UpdateModelRequest
    export type UpdateModelMutationError = unknown

    export const useUpdateModel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateModel>>, TError,{id: number;data: UpdateModelRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateModel>>,
        TError,
        {id: number;data: UpdateModelRequest},
        TContext
      > => {
      return useMutation(getUpdateModelMutationOptions(options), queryClient);
    }
    export const deleteModel = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/models/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteModelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModel>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteModel>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteModel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteModel>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteModel(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteModelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteModel>>>
    
    export type DeleteModelMutationError = unknown

    export const useDeleteModel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModel>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteModel>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteModelMutationOptions(options), queryClient);
    }
    