/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  BrandResponse,
  CreateBrandRequest,
  SearchBrandParams,
  UpdateBrandRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getBrandById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<BrandResponse>(
      {url: `/api/brands/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetBrandByIdQueryKey = (id: number,) => {
    return [
    `/api/brands/${id}`
    ] as const;
    }

    
export const getGetBrandByIdQueryOptions = <TData = Awaited<ReturnType<typeof getBrandById>>, TError = ApiError>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBrandByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBrandById>>> = ({ signal }) => getBrandById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBrandById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBrandByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getBrandById>>>
export type GetBrandByIdQueryError = ApiError


export function useGetBrandById<TData = Awaited<ReturnType<typeof getBrandById>>, TError = ApiError>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandById>>,
          TError,
          Awaited<ReturnType<typeof getBrandById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBrandById<TData = Awaited<ReturnType<typeof getBrandById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandById>>,
          TError,
          Awaited<ReturnType<typeof getBrandById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBrandById<TData = Awaited<ReturnType<typeof getBrandById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBrandById<TData = Awaited<ReturnType<typeof getBrandById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBrandByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateBrand = (
    id: number,
    updateBrandRequest: UpdateBrandRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<BrandResponse>(
      {url: `/api/brands/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateBrandRequest, signal
    },
      );
    }
  


export const getUpdateBrandMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBrand>>, TError,{id: number;data: UpdateBrandRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateBrand>>, TError,{id: number;data: UpdateBrandRequest}, TContext> => {

const mutationKey = ['updateBrand'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBrand>>, {id: number;data: UpdateBrandRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBrand(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBrandMutationResult = NonNullable<Awaited<ReturnType<typeof updateBrand>>>
    export type UpdateBrandMutationBody = UpdateBrandRequest
    export type UpdateBrandMutationError = ApiError

    export const useUpdateBrand = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBrand>>, TError,{id: number;data: UpdateBrandRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBrand>>,
        TError,
        {id: number;data: UpdateBrandRequest},
        TContext
      > => {
      return useMutation(getUpdateBrandMutationOptions(options), queryClient);
    }
    export const deleteBrand = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/brands/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteBrandMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBrand>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteBrand>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteBrand'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBrand>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteBrand(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBrandMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBrand>>>
    
    export type DeleteBrandMutationError = ApiError

    export const useDeleteBrand = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBrand>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBrand>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteBrandMutationOptions(options), queryClient);
    }
    export const getAllBrands = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<BrandResponse[]>(
      {url: `/api/brands`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllBrandsQueryKey = () => {
    return [
    `/api/brands`
    ] as const;
    }

    
export const getGetAllBrandsQueryOptions = <TData = Awaited<ReturnType<typeof getAllBrands>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBrands>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBrandsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBrands>>> = ({ signal }) => getAllBrands(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBrands>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBrandsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBrands>>>
export type GetAllBrandsQueryError = ApiError


export function useGetAllBrands<TData = Awaited<ReturnType<typeof getAllBrands>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBrands>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBrands>>,
          TError,
          Awaited<ReturnType<typeof getAllBrands>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBrands<TData = Awaited<ReturnType<typeof getAllBrands>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBrands>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBrands>>,
          TError,
          Awaited<ReturnType<typeof getAllBrands>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBrands<TData = Awaited<ReturnType<typeof getAllBrands>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBrands>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllBrands<TData = Awaited<ReturnType<typeof getAllBrands>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBrands>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBrandsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const createBrand = (
    createBrandRequest: CreateBrandRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<BrandResponse>(
      {url: `/api/brands`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBrandRequest, signal
    },
      );
    }
  


export const getCreateBrandMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBrand>>, TError,{data: CreateBrandRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createBrand>>, TError,{data: CreateBrandRequest}, TContext> => {

const mutationKey = ['createBrand'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBrand>>, {data: CreateBrandRequest}> = (props) => {
          const {data} = props ?? {};

          return  createBrand(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBrandMutationResult = NonNullable<Awaited<ReturnType<typeof createBrand>>>
    export type CreateBrandMutationBody = CreateBrandRequest
    export type CreateBrandMutationError = ApiError

    export const useCreateBrand = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBrand>>, TError,{data: CreateBrandRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBrand>>,
        TError,
        {data: CreateBrandRequest},
        TContext
      > => {
      return useMutation(getCreateBrandMutationOptions(options), queryClient);
    }
    export const searchBrand = (
    params: SearchBrandParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<BrandResponse[]>(
      {url: `/api/brands/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchBrandQueryKey = (params?: SearchBrandParams,) => {
    return [
    `/api/brands/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchBrandQueryOptions = <TData = Awaited<ReturnType<typeof searchBrand>>, TError = ApiError>(params: SearchBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBrand>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchBrandQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchBrand>>> = ({ signal }) => searchBrand(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchBrand>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchBrandQueryResult = NonNullable<Awaited<ReturnType<typeof searchBrand>>>
export type SearchBrandQueryError = ApiError


export function useSearchBrand<TData = Awaited<ReturnType<typeof searchBrand>>, TError = ApiError>(
 params: SearchBrandParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBrand>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchBrand>>,
          TError,
          Awaited<ReturnType<typeof searchBrand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchBrand<TData = Awaited<ReturnType<typeof searchBrand>>, TError = ApiError>(
 params: SearchBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBrand>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchBrand>>,
          TError,
          Awaited<ReturnType<typeof searchBrand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchBrand<TData = Awaited<ReturnType<typeof searchBrand>>, TError = ApiError>(
 params: SearchBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBrand>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchBrand<TData = Awaited<ReturnType<typeof searchBrand>>, TError = ApiError>(
 params: SearchBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchBrand>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchBrandQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getBrandByName = (
    nome: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<BrandResponse>(
      {url: `/api/brands/by-name/${nome}`, method: 'GET', signal
    },
      );
    }
  



export const getGetBrandByNameQueryKey = (nome: string,) => {
    return [
    `/api/brands/by-name/${nome}`
    ] as const;
    }

    
export const getGetBrandByNameQueryOptions = <TData = Awaited<ReturnType<typeof getBrandByName>>, TError = ApiError>(nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandByName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBrandByNameQueryKey(nome);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBrandByName>>> = ({ signal }) => getBrandByName(nome, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(nome), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBrandByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBrandByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getBrandByName>>>
export type GetBrandByNameQueryError = ApiError


export function useGetBrandByName<TData = Awaited<ReturnType<typeof getBrandByName>>, TError = ApiError>(
 nome: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandByName>>,
          TError,
          Awaited<ReturnType<typeof getBrandByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBrandByName<TData = Awaited<ReturnType<typeof getBrandByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBrandByName>>,
          TError,
          Awaited<ReturnType<typeof getBrandByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBrandByName<TData = Awaited<ReturnType<typeof getBrandByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandByName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBrandByName<TData = Awaited<ReturnType<typeof getBrandByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBrandByName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBrandByNameQueryOptions(nome,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




