/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  CreateModelRequest,
  ModelResponse,
  SearchModelByBrandNameParams,
  SearchModelByBrandParams,
  SearchModelParams,
  UpdateModelRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getModelById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/api/models/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetModelByIdQueryKey = (id: number,) => {
    return [
    `/api/models/${id}`
    ] as const;
    }

    
export const getGetModelByIdQueryOptions = <TData = Awaited<ReturnType<typeof getModelById>>, TError = ApiError>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModelByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModelById>>> = ({ signal }) => getModelById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModelByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getModelById>>>
export type GetModelByIdQueryError = ApiError


export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = ApiError>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelById>>,
          TError,
          Awaited<ReturnType<typeof getModelById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelById>>,
          TError,
          Awaited<ReturnType<typeof getModelById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetModelById<TData = Awaited<ReturnType<typeof getModelById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModelByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateModel = (
    id: number,
    updateModelRequest: UpdateModelRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/api/models/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateModelRequest, signal
    },
      );
    }
  


export const getUpdateModelMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateModel>>, TError,{id: number;data: UpdateModelRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateModel>>, TError,{id: number;data: UpdateModelRequest}, TContext> => {

const mutationKey = ['updateModel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateModel>>, {id: number;data: UpdateModelRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateModel(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateModelMutationResult = NonNullable<Awaited<ReturnType<typeof updateModel>>>
    export type UpdateModelMutationBody = UpdateModelRequest
    export type UpdateModelMutationError = ApiError

    export const useUpdateModel = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateModel>>, TError,{id: number;data: UpdateModelRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateModel>>,
        TError,
        {id: number;data: UpdateModelRequest},
        TContext
      > => {
      return useMutation(getUpdateModelMutationOptions(options), queryClient);
    }
    export const deleteModel = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/models/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteModelMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModel>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteModel>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteModel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteModel>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteModel(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteModelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteModel>>>
    
    export type DeleteModelMutationError = ApiError

    export const useDeleteModel = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModel>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteModel>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteModelMutationOptions(options), queryClient);
    }
    export const getAllModels = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/api/models`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllModelsQueryKey = () => {
    return [
    `/api/models`
    ] as const;
    }

    
export const getGetAllModelsQueryOptions = <TData = Awaited<ReturnType<typeof getAllModels>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllModelsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllModels>>> = ({ signal }) => getAllModels(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllModelsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllModels>>>
export type GetAllModelsQueryError = ApiError


export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllModels>>,
          TError,
          Awaited<ReturnType<typeof getAllModels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllModels>>,
          TError,
          Awaited<ReturnType<typeof getAllModels>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllModels<TData = Awaited<ReturnType<typeof getAllModels>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllModels>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllModelsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const createModel = (
    createModelRequest: CreateModelRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/api/models`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createModelRequest, signal
    },
      );
    }
  


export const getCreateModelMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createModel>>, TError,{data: CreateModelRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createModel>>, TError,{data: CreateModelRequest}, TContext> => {

const mutationKey = ['createModel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createModel>>, {data: CreateModelRequest}> = (props) => {
          const {data} = props ?? {};

          return  createModel(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateModelMutationResult = NonNullable<Awaited<ReturnType<typeof createModel>>>
    export type CreateModelMutationBody = CreateModelRequest
    export type CreateModelMutationError = ApiError

    export const useCreateModel = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createModel>>, TError,{data: CreateModelRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createModel>>,
        TError,
        {data: CreateModelRequest},
        TContext
      > => {
      return useMutation(getCreateModelMutationOptions(options), queryClient);
    }
    export const searchModel = (
    params: SearchModelParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/api/models/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchModelQueryKey = (params?: SearchModelParams,) => {
    return [
    `/api/models/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchModelQueryOptions = <TData = Awaited<ReturnType<typeof searchModel>>, TError = ApiError>(params: SearchModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModel>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchModelQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchModel>>> = ({ signal }) => searchModel(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchModel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchModelQueryResult = NonNullable<Awaited<ReturnType<typeof searchModel>>>
export type SearchModelQueryError = ApiError


export function useSearchModel<TData = Awaited<ReturnType<typeof searchModel>>, TError = ApiError>(
 params: SearchModelParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModel>>,
          TError,
          Awaited<ReturnType<typeof searchModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModel<TData = Awaited<ReturnType<typeof searchModel>>, TError = ApiError>(
 params: SearchModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModel>>,
          TError,
          Awaited<ReturnType<typeof searchModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModel<TData = Awaited<ReturnType<typeof searchModel>>, TError = ApiError>(
 params: SearchModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchModel<TData = Awaited<ReturnType<typeof searchModel>>, TError = ApiError>(
 params: SearchModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModel>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchModelQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchModelByBrand = (
    params: SearchModelByBrandParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/api/models/search/by-brand`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchModelByBrandQueryKey = (params?: SearchModelByBrandParams,) => {
    return [
    `/api/models/search/by-brand`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchModelByBrandQueryOptions = <TData = Awaited<ReturnType<typeof searchModelByBrand>>, TError = ApiError>(params: SearchModelByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrand>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchModelByBrandQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchModelByBrand>>> = ({ signal }) => searchModelByBrand(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrand>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchModelByBrandQueryResult = NonNullable<Awaited<ReturnType<typeof searchModelByBrand>>>
export type SearchModelByBrandQueryError = ApiError


export function useSearchModelByBrand<TData = Awaited<ReturnType<typeof searchModelByBrand>>, TError = ApiError>(
 params: SearchModelByBrandParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrand>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelByBrand>>,
          TError,
          Awaited<ReturnType<typeof searchModelByBrand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelByBrand<TData = Awaited<ReturnType<typeof searchModelByBrand>>, TError = ApiError>(
 params: SearchModelByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrand>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelByBrand>>,
          TError,
          Awaited<ReturnType<typeof searchModelByBrand>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelByBrand<TData = Awaited<ReturnType<typeof searchModelByBrand>>, TError = ApiError>(
 params: SearchModelByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrand>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchModelByBrand<TData = Awaited<ReturnType<typeof searchModelByBrand>>, TError = ApiError>(
 params: SearchModelByBrandParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrand>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchModelByBrandQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchModelByBrandName = (
    params: SearchModelByBrandNameParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/api/models/search/by-brand-name`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchModelByBrandNameQueryKey = (params?: SearchModelByBrandNameParams,) => {
    return [
    `/api/models/search/by-brand-name`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchModelByBrandNameQueryOptions = <TData = Awaited<ReturnType<typeof searchModelByBrandName>>, TError = ApiError>(params: SearchModelByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrandName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchModelByBrandNameQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchModelByBrandName>>> = ({ signal }) => searchModelByBrandName(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrandName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchModelByBrandNameQueryResult = NonNullable<Awaited<ReturnType<typeof searchModelByBrandName>>>
export type SearchModelByBrandNameQueryError = ApiError


export function useSearchModelByBrandName<TData = Awaited<ReturnType<typeof searchModelByBrandName>>, TError = ApiError>(
 params: SearchModelByBrandNameParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrandName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelByBrandName>>,
          TError,
          Awaited<ReturnType<typeof searchModelByBrandName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelByBrandName<TData = Awaited<ReturnType<typeof searchModelByBrandName>>, TError = ApiError>(
 params: SearchModelByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrandName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchModelByBrandName>>,
          TError,
          Awaited<ReturnType<typeof searchModelByBrandName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchModelByBrandName<TData = Awaited<ReturnType<typeof searchModelByBrandName>>, TError = ApiError>(
 params: SearchModelByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrandName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchModelByBrandName<TData = Awaited<ReturnType<typeof searchModelByBrandName>>, TError = ApiError>(
 params: SearchModelByBrandNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchModelByBrandName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchModelByBrandNameQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getModelByName = (
    nome: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse>(
      {url: `/api/models/by-name/${nome}`, method: 'GET', signal
    },
      );
    }
  



export const getGetModelByNameQueryKey = (nome: string,) => {
    return [
    `/api/models/by-name/${nome}`
    ] as const;
    }

    
export const getGetModelByNameQueryOptions = <TData = Awaited<ReturnType<typeof getModelByName>>, TError = ApiError>(nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModelByNameQueryKey(nome);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModelByName>>> = ({ signal }) => getModelByName(nome, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(nome), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModelByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getModelByName>>>
export type GetModelByNameQueryError = ApiError


export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = ApiError>(
 nome: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelByName>>,
          TError,
          Awaited<ReturnType<typeof getModelByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelByName>>,
          TError,
          Awaited<ReturnType<typeof getModelByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetModelByName<TData = Awaited<ReturnType<typeof getModelByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelByName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModelByNameQueryOptions(nome,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getModelsByBrandId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelResponse[]>(
      {url: `/api/models/by-brand-id/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetModelsByBrandIdQueryKey = (id: number,) => {
    return [
    `/api/models/by-brand-id/${id}`
    ] as const;
    }

    
export const getGetModelsByBrandIdQueryOptions = <TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = ApiError>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModelsByBrandIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModelsByBrandId>>> = ({ signal }) => getModelsByBrandId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModelsByBrandIdQueryResult = NonNullable<Awaited<ReturnType<typeof getModelsByBrandId>>>
export type GetModelsByBrandIdQueryError = ApiError


export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = ApiError>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelsByBrandId>>,
          TError,
          Awaited<ReturnType<typeof getModelsByBrandId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModelsByBrandId>>,
          TError,
          Awaited<ReturnType<typeof getModelsByBrandId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetModelsByBrandId<TData = Awaited<ReturnType<typeof getModelsByBrandId>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModelsByBrandId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModelsByBrandIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




