/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gestionale Negozio API
 * API del gestionale negozio
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiError,
  CreateInterventionRequest,
  InterventionResponse,
  SearchInterventionByModelParams,
  SearchInterventionParams,
  UpdateInterventionRequest
} from '../../models';

import { axiosInstance } from '../../axiosInstance';




export const getInterventionById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/api/interventions/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventionByIdQueryKey = (id: number,) => {
    return [
    `/api/interventions/${id}`
    ] as const;
    }

    
export const getGetInterventionByIdQueryOptions = <TData = Awaited<ReturnType<typeof getInterventionById>>, TError = ApiError>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventionByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventionById>>> = ({ signal }) => getInterventionById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventionById>>>
export type GetInterventionByIdQueryError = ApiError


export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = ApiError>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionById>>,
          TError,
          Awaited<ReturnType<typeof getInterventionById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionById>>,
          TError,
          Awaited<ReturnType<typeof getInterventionById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventionById<TData = Awaited<ReturnType<typeof getInterventionById>>, TError = ApiError>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventionByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const updateIntervention = (
    id: number,
    updateInterventionRequest: UpdateInterventionRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/api/interventions/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateInterventionRequest, signal
    },
      );
    }
  


export const getUpdateInterventionMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIntervention>>, TError,{id: number;data: UpdateInterventionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateIntervention>>, TError,{id: number;data: UpdateInterventionRequest}, TContext> => {

const mutationKey = ['updateIntervention'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateIntervention>>, {id: number;data: UpdateInterventionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateIntervention(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateInterventionMutationResult = NonNullable<Awaited<ReturnType<typeof updateIntervention>>>
    export type UpdateInterventionMutationBody = UpdateInterventionRequest
    export type UpdateInterventionMutationError = ApiError

    export const useUpdateIntervention = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateIntervention>>, TError,{id: number;data: UpdateInterventionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateIntervention>>,
        TError,
        {id: number;data: UpdateInterventionRequest},
        TContext
      > => {
      return useMutation(getUpdateInterventionMutationOptions(options), queryClient);
    }
    export const deleteIntervention = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/interventions/${id}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteInterventionMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIntervention>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteIntervention>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteIntervention'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIntervention>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteIntervention(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteInterventionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIntervention>>>
    
    export type DeleteInterventionMutationError = ApiError

    export const useDeleteIntervention = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIntervention>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteIntervention>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteInterventionMutationOptions(options), queryClient);
    }
    export const getAllInterventions = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/api/interventions`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllInterventionsQueryKey = () => {
    return [
    `/api/interventions`
    ] as const;
    }

    
export const getGetAllInterventionsQueryOptions = <TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllInterventionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllInterventions>>> = ({ signal }) => getAllInterventions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllInterventionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllInterventions>>>
export type GetAllInterventionsQueryError = ApiError


export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllInterventions>>,
          TError,
          Awaited<ReturnType<typeof getAllInterventions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllInterventions>>,
          TError,
          Awaited<ReturnType<typeof getAllInterventions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllInterventions<TData = Awaited<ReturnType<typeof getAllInterventions>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllInterventions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllInterventionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const createIntervention = (
    createInterventionRequest: CreateInterventionRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/api/interventions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInterventionRequest, signal
    },
      );
    }
  


export const getCreateInterventionMutationOptions = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIntervention>>, TError,{data: CreateInterventionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createIntervention>>, TError,{data: CreateInterventionRequest}, TContext> => {

const mutationKey = ['createIntervention'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIntervention>>, {data: CreateInterventionRequest}> = (props) => {
          const {data} = props ?? {};

          return  createIntervention(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateInterventionMutationResult = NonNullable<Awaited<ReturnType<typeof createIntervention>>>
    export type CreateInterventionMutationBody = CreateInterventionRequest
    export type CreateInterventionMutationError = ApiError

    export const useCreateIntervention = <TError = ApiError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIntervention>>, TError,{data: CreateInterventionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createIntervention>>,
        TError,
        {data: CreateInterventionRequest},
        TContext
      > => {
      return useMutation(getCreateInterventionMutationOptions(options), queryClient);
    }
    export const searchIntervention = (
    params: SearchInterventionParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/api/interventions/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchInterventionQueryKey = (params?: SearchInterventionParams,) => {
    return [
    `/api/interventions/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchInterventionQueryOptions = <TData = Awaited<ReturnType<typeof searchIntervention>>, TError = ApiError>(params: SearchInterventionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchIntervention>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchInterventionQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchIntervention>>> = ({ signal }) => searchIntervention(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchIntervention>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchInterventionQueryResult = NonNullable<Awaited<ReturnType<typeof searchIntervention>>>
export type SearchInterventionQueryError = ApiError


export function useSearchIntervention<TData = Awaited<ReturnType<typeof searchIntervention>>, TError = ApiError>(
 params: SearchInterventionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchIntervention>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchIntervention>>,
          TError,
          Awaited<ReturnType<typeof searchIntervention>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchIntervention<TData = Awaited<ReturnType<typeof searchIntervention>>, TError = ApiError>(
 params: SearchInterventionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchIntervention>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchIntervention>>,
          TError,
          Awaited<ReturnType<typeof searchIntervention>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchIntervention<TData = Awaited<ReturnType<typeof searchIntervention>>, TError = ApiError>(
 params: SearchInterventionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchIntervention>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchIntervention<TData = Awaited<ReturnType<typeof searchIntervention>>, TError = ApiError>(
 params: SearchInterventionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchIntervention>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchInterventionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const searchInterventionByModel = (
    params: SearchInterventionByModelParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/api/interventions/search/by-model`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchInterventionByModelQueryKey = (params?: SearchInterventionByModelParams,) => {
    return [
    `/api/interventions/search/by-model`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchInterventionByModelQueryOptions = <TData = Awaited<ReturnType<typeof searchInterventionByModel>>, TError = ApiError>(params: SearchInterventionByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionByModel>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchInterventionByModelQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchInterventionByModel>>> = ({ signal }) => searchInterventionByModel(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchInterventionByModel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchInterventionByModelQueryResult = NonNullable<Awaited<ReturnType<typeof searchInterventionByModel>>>
export type SearchInterventionByModelQueryError = ApiError


export function useSearchInterventionByModel<TData = Awaited<ReturnType<typeof searchInterventionByModel>>, TError = ApiError>(
 params: SearchInterventionByModelParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionByModel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInterventionByModel>>,
          TError,
          Awaited<ReturnType<typeof searchInterventionByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchInterventionByModel<TData = Awaited<ReturnType<typeof searchInterventionByModel>>, TError = ApiError>(
 params: SearchInterventionByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionByModel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchInterventionByModel>>,
          TError,
          Awaited<ReturnType<typeof searchInterventionByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchInterventionByModel<TData = Awaited<ReturnType<typeof searchInterventionByModel>>, TError = ApiError>(
 params: SearchInterventionByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionByModel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchInterventionByModel<TData = Awaited<ReturnType<typeof searchInterventionByModel>>, TError = ApiError>(
 params: SearchInterventionByModelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchInterventionByModel>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchInterventionByModelQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInterventiGenerali = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/api/interventions/generali`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventiGeneraliQueryKey = () => {
    return [
    `/api/interventions/generali`
    ] as const;
    }

    
export const getGetInterventiGeneraliQueryOptions = <TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = ApiError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventiGeneraliQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventiGenerali>>> = ({ signal }) => getInterventiGenerali(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventiGeneraliQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventiGenerali>>>
export type GetInterventiGeneraliQueryError = ApiError


export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = ApiError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventiGenerali>>,
          TError,
          Awaited<ReturnType<typeof getInterventiGenerali>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventiGenerali>>,
          TError,
          Awaited<ReturnType<typeof getInterventiGenerali>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventiGenerali<TData = Awaited<ReturnType<typeof getInterventiGenerali>>, TError = ApiError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventiGenerali>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventiGeneraliQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInterventionByName = (
    nome: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse>(
      {url: `/api/interventions/by-name/${nome}`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventionByNameQueryKey = (nome: string,) => {
    return [
    `/api/interventions/by-name/${nome}`
    ] as const;
    }

    
export const getGetInterventionByNameQueryOptions = <TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = ApiError>(nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventionByNameQueryKey(nome);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventionByName>>> = ({ signal }) => getInterventionByName(nome, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(nome), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventionByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventionByName>>>
export type GetInterventionByNameQueryError = ApiError


export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = ApiError>(
 nome: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionByName>>,
          TError,
          Awaited<ReturnType<typeof getInterventionByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionByName>>,
          TError,
          Awaited<ReturnType<typeof getInterventionByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventionByName<TData = Awaited<ReturnType<typeof getInterventionByName>>, TError = ApiError>(
 nome: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionByName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventionByNameQueryOptions(nome,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getInterventionsByModel = (
    modelId: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<InterventionResponse[]>(
      {url: `/api/interventions/by-model/${modelId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetInterventionsByModelQueryKey = (modelId: number,) => {
    return [
    `/api/interventions/by-model/${modelId}`
    ] as const;
    }

    
export const getGetInterventionsByModelQueryOptions = <TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = ApiError>(modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterventionsByModelQueryKey(modelId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterventionsByModel>>> = ({ signal }) => getInterventionsByModel(modelId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(modelId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterventionsByModelQueryResult = NonNullable<Awaited<ReturnType<typeof getInterventionsByModel>>>
export type GetInterventionsByModelQueryError = ApiError


export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = ApiError>(
 modelId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionsByModel>>,
          TError,
          Awaited<ReturnType<typeof getInterventionsByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = ApiError>(
 modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterventionsByModel>>,
          TError,
          Awaited<ReturnType<typeof getInterventionsByModel>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = ApiError>(
 modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetInterventionsByModel<TData = Awaited<ReturnType<typeof getInterventionsByModel>>, TError = ApiError>(
 modelId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterventionsByModel>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterventionsByModelQueryOptions(modelId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




