openapi: 3.1.0
info:
  title: Gestionale Negozio API
  description: API del gestionale negozio
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/models/{id}:
    get:
      tags:
      - model-controller
      operationId: getModelById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ModelResponse"
    put:
      tags:
      - model-controller
      operationId: updateModel
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateModelRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ModelResponse"
    delete:
      tags:
      - model-controller
      operationId: deleteModel
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/customers/{id}:
    get:
      tags:
      - customer-controller
      operationId: getCustomerById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerResponse"
    put:
      tags:
      - customer-controller
      operationId: updateCustomer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCustomerRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerResponse"
    delete:
      tags:
      - customer-controller
      operationId: deleteCustomer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/brands/{id}:
    get:
      tags:
      - brand-controller
      operationId: getBrandById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BrandResponse"
    put:
      tags:
      - brand-controller
      operationId: updateBrand
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBrandRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BrandResponse"
    delete:
      tags:
      - brand-controller
      operationId: deleteBrand
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/models:
    get:
      tags:
      - model-controller
      operationId: getAllModels
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ModelResponse"
    post:
      tags:
      - model-controller
      operationId: createModel
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateModelRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ModelResponse"
  /api/customers:
    get:
      tags:
      - customer-controller
      operationId: getAllCustomers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerResponse"
    post:
      tags:
      - customer-controller
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCustomerRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerResponse"
  /api/brands:
    get:
      tags:
      - brand-controller
      operationId: getAllBrands
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BrandResponse"
    post:
      tags:
      - brand-controller
      operationId: createBrand
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBrandRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BrandResponse"
  /api/auth/register:
    post:
      tags:
      - auth-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "200":
          description: OK
  /api/auth/login:
    post:
      tags:
      - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /api/models/search:
    get:
      tags:
      - model-controller
      operationId: searchModel
      parameters:
      - name: nome
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ModelResponse"
  /api/models/search/by-brand:
    get:
      tags:
      - model-controller
      operationId: searchModelByBrand
      parameters:
      - name: brandId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: nome
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ModelResponse"
  /api/models/by-name/{nome}:
    get:
      tags:
      - model-controller
      operationId: getModelByName
      parameters:
      - name: nome
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ModelResponse"
  /api/models/by-brand-id/{id}:
    get:
      tags:
      - model-controller
      operationId: getModelsByBrandId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ModelResponse"
  /api/health:
    get:
      tags:
      - health-check-controller
      operationId: healthCheck
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /api/brands/search:
    get:
      tags:
      - brand-controller
      operationId: searchBrand
      parameters:
      - name: nome
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BrandResponse"
  /api/brands/by-name/{nome}:
    get:
      tags:
      - brand-controller
      operationId: getBrandByName
      parameters:
      - name: nome
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BrandResponse"
components:
  schemas:
    UpdateModelRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
        brandId:
          type: integer
          format: int64
      required:
      - brandId
      - nome
    ModelResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
          minLength: 1
        brandId:
          type: integer
          format: int64
        brandNome:
          type: string
          minLength: 1
      required:
      - brandId
      - brandNome
      - id
      - nome
    UpdateCustomerRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
        cognome:
          type: string
          minLength: 1
        email:
          type: string
          format: email
          minLength: 1
        indirizzo:
          type: string
        citta:
          type: string
        cap:
          type: string
          pattern: "\\d{5}"
        telefono:
          type: string
          minLength: 1
        telefonoSecondario:
          type: string
      required:
      - cognome
      - email
      - nome
      - telefono
    CustomerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
          minLength: 1
        cognome:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        indirizzo:
          type: string
        citta:
          type: string
        cap:
          type: string
        telefono:
          type: string
          minLength: 1
        telefonoSecondario:
          type: string
      required:
      - cognome
      - email
      - id
      - nome
      - telefono
    UpdateBrandRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
      required:
      - nome
    BrandResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
          minLength: 1
      required:
      - id
      - nome
    CreateModelRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
        brandId:
          type: integer
          format: int64
      required:
      - brandId
      - nome
    CreateCustomerRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
        cognome:
          type: string
          minLength: 1
        email:
          type: string
          format: email
          minLength: 1
        indirizzo:
          type: string
        citta:
          type: string
        cap:
          type: string
          pattern: "\\d{5}"
        telefono:
          type: string
          minLength: 1
        telefonoSecondario:
          type: string
      required:
      - cognome
      - email
      - nome
      - telefono
    CreateBrandRequest:
      type: object
      properties:
        nome:
          type: string
          minLength: 1
      required:
      - nome
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - password
      - username
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - password
      - username
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          minLength: 1
      required:
      - token
